from cdpython import make_path

assert make_path("/", "abc") == "/abc"
assert make_path("/abc/def", "ghi") == "/abc/def/ghi"
assert make_path("/abc/def", "..") == "/abc"
assert make_path("/abc/def", "/abc") == "/abc"
assert make_path("/abc/def", "/abc/klm") == "/abc/klm"
assert make_path("/abc/def", "../..") == "/"
assert make_path("/abc/def", "../../..") == "/"
assert make_path("/abc/def", ".") == "/abc/def"
assert make_path("/abc/def", "..klm") == "..klm: No such file or directory"
assert make_path("/abc/def", "/////") == "/"
assert make_path("/abc/def", "../gh///../klm/.") == "/abc/klm"
assert make_path("/aaa/bbb/ccc", "ddd") == "/aaa/bbb/ccc/ddd"
assert make_path("/a/b/c", "d") == "/a/b/c/d"
